export const COMPANIES: string[] = [
  "5K Network",
  "Accenture",
  "Agilysis",
  "Amazon",
  "Avasoft",
  "Beyond Universe Software",
  "Bosch",
  "Cadence",
  "Capgemini",
  "Chiptest Engineering Pvt. Ltd.",
  "Cognizant",
  "Conserve Solutions",
  "Cube Simple",
  "Deloitte",
  "Diya Robotics",
  "EY",
  "Expeditors",
  "FedERAL Bank",
  "Genxlead Solutions Pvt. Ltd.",
  "Gates Unitta India Pvt. Ltd.",
  "Hakuna Matata",
  "HCL",
  "Hexaware Technologies",
  "Infosys",
  "JBM Auto Pvt. Ltd.",
  "Just Connect Electrical Pvt. Ltd.",
  "K.K. Precision Components",
  "LatentView Analytics",
  "L&T Infotech",
  "Magic Reach Technologies",
  "Maestro Steel Detailing",
  "Mindtree",
  "Mobius 365 Data Services",
  "Nokia",
  "Omega Healthcare",
  "Pinstar Automotive India Pvt. Ltd.",
  "Propel",
  "Q-Spiders",
  "Renault Nissan Technologies",
  "Rialto Enterprises Pvt. Ltd.",
  "Sagictec Solutions",
  "Skylark HR Solutions Pvt. Ltd.",
  "SL-Lumax",
  "Soliton Technologies",
  "Skill Lyc",
  "Sintex BAPL Ltd.",
  "TCS",
  "Techmahindra",
  "U-Plus Technologies India Pvt. Ltd.",
  "Vectone India Ltd.",
  "Wipro",
  "Wipro Technologies",
  "Zoho",
];
